# Settings

exclude:
  - README.md
  - Makefile
  - Gemfile*
  - vendor/
  - info.sublime-*

paginate:   5

markdown:       redcarpet
highlighter:    rouge
gems:
  - jekyll-paginate

permalink:              pretty

# Routes

url:        https://jacebrowning.info
baseurl:    /
downloads:  /downloads
assets:     /assets

# Content

title:          Jace Browning
tagline:        "Software Craftsman"
description:    "I build, customize, integrate, and teach engineering software tools."

author:
  name:         "Jace Browning"
  twitter:      https://twitter.com/jacebrowning
  linkedin:     https://www.linkedin.com/in/jacebrowning
  speakerdeck:  https://speakerdeck.com/jacebrowning
