# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty
relative_permalinks: true

# Setup
title:            Jace Browning
tagline:          'Software Craftsman'
description:      'I build, customize, integrate, and teach engineering software tools.'
url:              http://jacebrowning.info
baseurl:          /
downloads:        /downloads

author:
  name:           'Jace Browning'
  twitter:        https://twitter.com/jacebrowning
  speakerdeck:    https://speakerdeck.com/jacebrowning

paginate:         5
